---
title: "Class 6 R Functions"
author: "Danielle Garshott"
date: "1/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## File reading (again!)

```{r}
read.table("https://bioboot.github.io/bggn213_S18/class-material/test1.txt", header=TRUE, sep=",")
```

```{r}
file1 <- "https://bioboot.github.io/bggn213_S18/class-material/test1.txt"
read.csv(file1)
```

```{r}
file2 <- "https://bioboot.github.io/bggn213_S18/class-material/test2.txt"
read.table(file2, header=TRUE, sep="$")
```

```{r}
file3 <- "https://bioboot.github.io/bggn213_S18/class-material/test3.txt"
read.table(file3)
```

## R Functions

My first function

```{r}
add <- function(x, y=1) {
 # Sum the input x and y
 x + y}
```

Lets use the **add()** function'

```{r}
add(1)
```
```{r}
add(c(1,2,3,4))
```

```{r}
add(c(1,2,3,4),4)
#changes y=4
```

```{r}
#add(x=1, y="b")
```

# Our 2nd function 
```{r}
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}
```

```{r}
rescale(1:10)
```


```{r}
#How would the function work here....
rescale(c(1,2,NA,3,10))
```

```{r}
x <- c(1,2,NA,3,10)
rescale <- function(x) {
 rng <-range(x)
 (x - rng[1]) / (rng[2] - rng[1])
}

#(x - rng[1]) / (rng[2] - rng[1])

```

```{r}
rescale2 <- function(x) {
 rng <-range(x, na.rm=TRUE)
 (x - rng[1]) / (rng[2] - rng[1])
}
```
```{r}
rescale2(c(1,2,NA,3,10))
```

```{r}
#string
#rescale2(c(1,2,NA,3,10, "bggn213"))
```

```{r}
rescale3 <- function(x, na.rm=TRUE, plot=FALSE) {
 if(na.rm) {
 rng <-range(x, na.rm=na.rm)
 } else {
 rng <-range(x)
 }
 print("Hello")
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 print("is it me you are looking for?")
if(plot) {
 plot(answer, typ="b", lwd=4)
   print("please dont ever sing again!")
 }
 
 print("I can see it in ...")
}


```

```{r}
rescale3(1:10, plot=TRUE)
```


#Section 2B:
##Using the bio3d package
```{r}
library(bio3d)
```


```{r}
pdb <- read.pdb("1hbs")
```

What is in **pdb** R package?
```{r}
pdb
```

```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")

s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b

plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

#Trim function cuts down a big function into a smaller subset

```{r}
library(bio3d)
x <- read.pdb("4AKE") # kinase with drug

protein <- function() {
  x.chainA <- trim.pdb(x, chain="A", elety="CA")
  x.b <- x.chainA$atom$b
  plotb3(x.b, sse=x.chainA, typ="l", ylab="Bfactor")
}
```


```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

rescale <- function(x, na.rm=TRUE) {
  
  chain <- trim.pdb(x, chain="A", elety="CA")
  B <- chain$atom$b
 plotb3(B, sse=chain, type="1", ylab="Bfactor")
}

```


```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug

x <- c(s1, s2, s3)
protein <- function(x) {
  protein_trim <- trim.pdb(x, chain="A", elety="CA")
  y <- protein_trim$atomb
  plotb3(y, sse=s1.chainA, typ="l", ylab="Bfactor")
}

```











